sudo: required
dist: focal
language: node_js
node_js:
  - "14.0"

services:
  - docker

cache: npm

before_script:
  - npm install

script:
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u _ -p $heroku_key registry.heroku.com;
    docker build -t registry.heroku.com/todo-app-node-ameer/web .;
    docker push registry.heroku.com/todo-app-node-ameer/web;
    fi
